pandancode/signatures

.gitignore
Hi guys, this is an easy approval
=> Added .env file and hidden it for storing pws and keys

config/routes.rb
=> added amin's route

app/models/individual.rb, db/migrate/20211123114250_create_individuals.rb, test/models/individual_test.rb
Guys have a look at the individial model especially validations
=> created individual model with related associations and validation

app/models/company.rb, app/models/individual.rb, app/models/user.rb, db/migrate/20211123114719_devise_create_users.rb, db/migrate/20211123114720_create_companies.rb, db/migrate/20211123114721_create_individuals.rb, db/migrate/20211123114723_create_contracts.rb, db/schema.rb, db/seeds.rb
=> Changed migrations & established seed file

app/controllers/users_controller.rb, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, config/routes.rb
Updated home page and sign up page for individuals and companies. Need approval
=> Updated home page

app/views/signatories/new.html.erb
just created view signatures folder and new.html.erb file
=> created signatories folder in view and new file

app/controllers/companies_controller.rb, app/controllers/individuals_controller.rb, app/views/companies/show.html.erb, app/views/individuals/show.html.erb
"fixed show in both individuals controller and companies controller"
=> Next branch

app/controllers/contracts_controller.rb, app/views/contracts/show.html.erb, config/routes.rb, db/migrate/20211123114723_create_contracts.rb, db/schema.rb, db/seeds.rb
=> interim save

app/controllers/contracts_controller.rb, app/views/contracts/index.html.erb, app/views/contracts/new.html.erb, app/views/contracts/show.html.erb
Please review, status thing is working now
=> Status is fully working

app/controllers/contracts_controller.rb, app/views/contracts/new.html.erb
Sarah, can you please review & merge?
=> Added ordering by latest contract first on index page

app/controllers/individuals_controller.rb
=> Fixed the individual signup process

app/controllers/contracts_controller.rb, db/migrate/20211123114723_create_contracts.rb
=> Manually copied changes from Amin

Gemfile, Gemfile.lock, app/views/layouts/pdf.html.erb, config/initializers/wicked_pdf.rb, cors.json, db/schema.rb
=> Heroku deployment fixes

Gemfile, Gemfile.lock, app/controllers/contracts_controller.rb, app/models/contract.rb, app/views/contracts/index.html.erb
=> Implemented a search bar (full words, not the prettiest code

app/controllers/individuals_controller.rb, app/views/individuals/_form.html.erb
=> Fixed signup process

app/controllers/contracts_controller.rb, app/views/companies/new.html.erb, app/views/companies/show.html.erb, app/views/contracts/new.html.erb, app/views/contracts/show.html.erb, app/views/contracts/unsigned.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, config/initializers/smtp.rb
=> Text and display changes

app/controllers/contracts_controller.rb, app/helpers/application_helper.rb, app/javascript/packs/application.js, app/views/shared/_flashes.html.erb, config/locales/devise.en.yml
=> Flashes details

app/views/contracts/_contracts.html.erb
=> fixed card link

app/assets/stylesheets/application.scss, app/assets/stylesheets/pdf_initials.scss, app/controllers/contracts_controller.rb, app/controllers/pdf_initials_controller.rb, app/views/pdf_initials/show.html.erb, config/routes.rb
=> Initials work

app/views/individuals/show.html.erb, app/views/layouts/application.html.erb, config/meta.yml
=> Brought back metatags, changed infos to details on edit page

app/views/pages/home.html.erb
=> extra line to why page

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/companies_controller.rb, app/controllers/contracts_controller.rb, app/controllers/individuals_controller.rb, app/policies/application_policy.rb, app/policies/company_policy.rb, app/policies/contract_policy.rb, app/policies/individual_policy.rb, config/routes.rb, test/policies/company_policy_test.rb, test/policies/contract_policy_test.rb, test/policies/individual_policy_test.rb
=> Pundit setup

app/views/companies/new.html.erb, app/views/contracts/show.html.erb, app/views/contracts/unsigned.html.erb, app/views/pdf_signatures/show.html.erb
=> Wording changes only + displaying status for cos until signing

app/assets/stylesheets/contracts/_index.scss
=> Optimized optics of searchbar

app/models/individual.rb
This is preparing for the Company (contract sender) to send emails to new people that are not in the database yet
=> Cut back on validations for the individual model

app/controllers/contracts_controller.rb, app/controllers/individuals_controller.rb, app/models/individual.rb, app/views/contracts/new.html.erb, app/views/individuals/show.html.erb, app/views/user_mailer/new_contract_received.html.erb, config/environments/development.rb, db/migrate/20211210175413_add_namefields_to_contract_table.rb, db/schema.rb
Added ability to email anyone (with title & name provided to create an individual, the other phone number & DoB validations have been suspended in the model for now)
=> Contract to new users

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/javascript/packs/application.js, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Navbar fully responsive with dynamic behavior on action icons implemented too. Works perfectly.
=> Navbar fully responsive DONE  ✅

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/contracts/_index.scss, app/assets/stylesheets/contracts/_new.scss, app/assets/stylesheets/contracts/_show.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/personal-details/_show.scss, app/assets/stylesheets/user-actions/_login.scss, app/javascript/packs/application.js, app/views/contracts/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Media queries for ALL the pages is finally done. Navbar included.
=> Media queries
